sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 7942Ud38

  alioss:
    bucket-name: itheima-sky-take-out
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI4GKKRZkaZk3FxcP9fiuZ
    access-key-secret: rkPgyyNqCFmXraP0xJTf4hB19zSQwC

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10

  wechat:
    appid: wx22622db794c168bc
    secret: 1ee823457c1213eb404a2563facbfb65
#    appid: wxffb3637a228223b8
#    secret: 84311df9199ecacdf4f12d27b6b9522d
    mchid : 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\weixin\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\weixin\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://144f9fe9.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://144f9fe9.cpolar.top/notify/refundSuccess

